// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/subdomain_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/subdomain_repo.go -destination=internal/mocks/mock_subdomain_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubdomainRepo is a mock of SubdomainRepo interface.
type MockSubdomainRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSubdomainRepoMockRecorder
	isgomock struct{}
}

// MockSubdomainRepoMockRecorder is the mock recorder for MockSubdomainRepo.
type MockSubdomainRepoMockRecorder struct {
	mock *MockSubdomainRepo
}

// NewMockSubdomainRepo creates a new mock instance.
func NewMockSubdomainRepo(ctrl *gomock.Controller) *MockSubdomainRepo {
	mock := &MockSubdomainRepo{ctrl: ctrl}
	mock.recorder = &MockSubdomainRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubdomainRepo) EXPECT() *MockSubdomainRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubdomainRepo) Create(subdomain *domain.Subdomain, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", subdomain, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubdomainRepoMockRecorder) Create(subdomain, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubdomainRepo)(nil).Create), subdomain, arg1)
}

// Delete mocks base method.
func (m *MockSubdomainRepo) Delete(subdomain *domain.Subdomain, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", subdomain, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubdomainRepoMockRecorder) Delete(subdomain, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubdomainRepo)(nil).Delete), subdomain, arg1)
}

// FindAllByUserID mocks base method.
func (m *MockSubdomainRepo) FindAllByUserID(userID string, arg1 context.Context) ([]domain.Subdomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", userID, arg1)
	ret0, _ := ret[0].([]domain.Subdomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockSubdomainRepoMockRecorder) FindAllByUserID(userID, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockSubdomainRepo)(nil).FindAllByUserID), userID, arg1)
}

// FindByFullDomain mocks base method.
func (m *MockSubdomainRepo) FindByFullDomain(arg0 string, arg1 context.Context) (*domain.Subdomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFullDomain", arg0, arg1)
	ret0, _ := ret[0].(*domain.Subdomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFullDomain indicates an expected call of FindByFullDomain.
func (mr *MockSubdomainRepoMockRecorder) FindByFullDomain(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFullDomain", reflect.TypeOf((*MockSubdomainRepo)(nil).FindByFullDomain), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockSubdomainRepo) FindByID(id string, arg1 context.Context) (*domain.Subdomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, arg1)
	ret0, _ := ret[0].(*domain.Subdomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubdomainRepoMockRecorder) FindByID(id, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubdomainRepo)(nil).FindByID), id, arg1)
}

// Update mocks base method.
func (m *MockSubdomainRepo) Update(id string, updates map[string]any, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubdomainRepoMockRecorder) Update(id, updates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubdomainRepo)(nil).Update), id, updates, arg2)
}
