// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/password_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/password_repo.go -destination=internal/mocks/mock_password_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasswordRepo is a mock of PasswordRepo interface.
type MockPasswordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordRepoMockRecorder
	isgomock struct{}
}

// MockPasswordRepoMockRecorder is the mock recorder for MockPasswordRepo.
type MockPasswordRepoMockRecorder struct {
	mock *MockPasswordRepo
}

// NewMockPasswordRepo creates a new mock instance.
func NewMockPasswordRepo(ctrl *gomock.Controller) *MockPasswordRepo {
	mock := &MockPasswordRepo{ctrl: ctrl}
	mock.recorder = &MockPasswordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordRepo) EXPECT() *MockPasswordRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordRepo) Create(pc *domain.PasswordCredential, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", pc, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordRepoMockRecorder) Create(pc, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordRepo)(nil).Create), pc, arg1)
}

// Delete mocks base method.
func (m *MockPasswordRepo) Delete(pc *domain.PasswordCredential, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", pc, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordRepoMockRecorder) Delete(pc, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordRepo)(nil).Delete), pc, arg1)
}

// FindById mocks base method.
func (m *MockPasswordRepo) FindById(id string, arg1 context.Context) (*domain.PasswordCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id, arg1)
	ret0, _ := ret[0].(*domain.PasswordCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockPasswordRepoMockRecorder) FindById(id, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockPasswordRepo)(nil).FindById), id, arg1)
}

// Update mocks base method.
func (m *MockPasswordRepo) Update(pc *domain.PasswordCredential, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", pc, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPasswordRepoMockRecorder) Update(pc, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPasswordRepo)(nil).Update), pc, arg1)
}
