// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/database_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/database_repo.go -destination=internal/mocks/mock_database_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseRepo is a mock of DatabaseRepo interface.
type MockDatabaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRepoMockRecorder
	isgomock struct{}
}

// MockDatabaseRepoMockRecorder is the mock recorder for MockDatabaseRepo.
type MockDatabaseRepoMockRecorder struct {
	mock *MockDatabaseRepo
}

// NewMockDatabaseRepo creates a new mock instance.
func NewMockDatabaseRepo(ctrl *gomock.Controller) *MockDatabaseRepo {
	mock := &MockDatabaseRepo{ctrl: ctrl}
	mock.recorder = &MockDatabaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRepo) EXPECT() *MockDatabaseRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDatabaseRepo) Create(db *domain.Database, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDatabaseRepoMockRecorder) Create(db, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatabaseRepo)(nil).Create), db, arg1)
}

// Delete mocks base method.
func (m *MockDatabaseRepo) Delete(db *domain.Database, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatabaseRepoMockRecorder) Delete(db, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatabaseRepo)(nil).Delete), db, arg1)
}

// FindByID mocks base method.
func (m *MockDatabaseRepo) FindByID(id string, arg1 context.Context) (*domain.Database, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, arg1)
	ret0, _ := ret[0].(*domain.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDatabaseRepoMockRecorder) FindByID(id, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDatabaseRepo)(nil).FindByID), id, arg1)
}

// FindBySubdomainID mocks base method.
func (m *MockDatabaseRepo) FindBySubdomainID(subdomainID string, arg1 context.Context) (*domain.Database, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubdomainID", subdomainID, arg1)
	ret0, _ := ret[0].(*domain.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubdomainID indicates an expected call of FindBySubdomainID.
func (mr *MockDatabaseRepoMockRecorder) FindBySubdomainID(subdomainID, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubdomainID", reflect.TypeOf((*MockDatabaseRepo)(nil).FindBySubdomainID), subdomainID, arg1)
}

// Update mocks base method.
func (m *MockDatabaseRepo) Update(id string, updates map[string]any, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseRepoMockRecorder) Update(id, updates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabaseRepo)(nil).Update), id, updates, arg2)
}
