// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/application_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/application_repo.go -destination=internal/mocks/mock_application_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApplicationRepo is a mock of ApplicationRepo interface.
type MockApplicationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepoMockRecorder
	isgomock struct{}
}

// MockApplicationRepoMockRecorder is the mock recorder for MockApplicationRepo.
type MockApplicationRepoMockRecorder struct {
	mock *MockApplicationRepo
}

// NewMockApplicationRepo creates a new mock instance.
func NewMockApplicationRepo(ctrl *gomock.Controller) *MockApplicationRepo {
	mock := &MockApplicationRepo{ctrl: ctrl}
	mock.recorder = &MockApplicationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepo) EXPECT() *MockApplicationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApplicationRepo) Create(app *domain.Application, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", app, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApplicationRepoMockRecorder) Create(app, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationRepo)(nil).Create), app, arg1)
}

// Delete mocks base method.
func (m *MockApplicationRepo) Delete(app *domain.Application, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", app, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApplicationRepoMockRecorder) Delete(app, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApplicationRepo)(nil).Delete), app, arg1)
}

// FindByID mocks base method.
func (m *MockApplicationRepo) FindByID(id string, arg1 context.Context) (*domain.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, arg1)
	ret0, _ := ret[0].(*domain.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockApplicationRepoMockRecorder) FindByID(id, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockApplicationRepo)(nil).FindByID), id, arg1)
}

// Update mocks base method.
func (m *MockApplicationRepo) Update(id string, updates map[string]any, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApplicationRepoMockRecorder) Update(id, updates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApplicationRepo)(nil).Update), id, updates, arg2)
}
