// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/jwt_tokenizer.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/jwt_tokenizer.go -destination=internal/mocks/mock_jwt_tokenizer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJwtTokenizer is a mock of JwtTokenizer interface.
type MockJwtTokenizer struct {
	ctrl     *gomock.Controller
	recorder *MockJwtTokenizerMockRecorder
	isgomock struct{}
}

// MockJwtTokenizerMockRecorder is the mock recorder for MockJwtTokenizer.
type MockJwtTokenizerMockRecorder struct {
	mock *MockJwtTokenizer
}

// NewMockJwtTokenizer creates a new mock instance.
func NewMockJwtTokenizer(ctrl *gomock.Controller) *MockJwtTokenizer {
	mock := &MockJwtTokenizer{ctrl: ctrl}
	mock.recorder = &MockJwtTokenizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtTokenizer) EXPECT() *MockJwtTokenizerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockJwtTokenizer) CreateToken(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockJwtTokenizerMockRecorder) CreateToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockJwtTokenizer)(nil).CreateToken), userID)
}

// VerifyToken mocks base method.
func (m *MockJwtTokenizer) VerifyToken(tokenStr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenStr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockJwtTokenizerMockRecorder) VerifyToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockJwtTokenizer)(nil).VerifyToken), tokenStr)
}
