// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/server_manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/server_manager.go -destination=internal/mocks/mock_server_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ports "api/internal/app/ports"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServerManagerClient is a mock of ServerManagerClient interface.
type MockServerManagerClient struct {
	ctrl     *gomock.Controller
	recorder *MockServerManagerClientMockRecorder
	isgomock struct{}
}

// MockServerManagerClientMockRecorder is the mock recorder for MockServerManagerClient.
type MockServerManagerClientMockRecorder struct {
	mock *MockServerManagerClient
}

// NewMockServerManagerClient creates a new mock instance.
func NewMockServerManagerClient(ctrl *gomock.Controller) *MockServerManagerClient {
	mock := &MockServerManagerClient{ctrl: ctrl}
	mock.recorder = &MockServerManagerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerManagerClient) EXPECT() *MockServerManagerClientMockRecorder {
	return m.recorder
}

// Logs mocks base method.
func (m *MockServerManagerClient) Logs(ctx context.Context, appID string, opts ports.LogOptions) ([]ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, appID, opts)
	ret0, _ := ret[0].([]ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockServerManagerClientMockRecorder) Logs(ctx, appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockServerManagerClient)(nil).Logs), ctx, appID, opts)
}

// StreamLogs mocks base method.
func (m *MockServerManagerClient) StreamLogs(ctx context.Context, appID string, opts ports.LogOptions) (<-chan ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamLogs", ctx, appID, opts)
	ret0, _ := ret[0].(<-chan ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamLogs indicates an expected call of StreamLogs.
func (mr *MockServerManagerClientMockRecorder) StreamLogs(ctx, appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLogs", reflect.TypeOf((*MockServerManagerClient)(nil).StreamLogs), ctx, appID, opts)
}
