// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/server_manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/server_manager.go -destination=internal/mocks/mock_server_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ports "api/internal/app/ports"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServerManagerClient is a mock of ServerManagerClient interface.
type MockServerManagerClient struct {
	ctrl     *gomock.Controller
	recorder *MockServerManagerClientMockRecorder
	isgomock struct{}
}

// MockServerManagerClientMockRecorder is the mock recorder for MockServerManagerClient.
type MockServerManagerClientMockRecorder struct {
	mock *MockServerManagerClient
}

// NewMockServerManagerClient creates a new mock instance.
func NewMockServerManagerClient(ctrl *gomock.Controller) *MockServerManagerClient {
	mock := &MockServerManagerClient{ctrl: ctrl}
	mock.recorder = &MockServerManagerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerManagerClient) EXPECT() *MockServerManagerClientMockRecorder {
	return m.recorder
}

// DatabaseLogs mocks base method.
func (m *MockServerManagerClient) DatabaseLogs(ctx context.Context, dbID string, opts ports.LogOptions) ([]ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseLogs", ctx, dbID, opts)
	ret0, _ := ret[0].([]ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseLogs indicates an expected call of DatabaseLogs.
func (mr *MockServerManagerClientMockRecorder) DatabaseLogs(ctx, dbID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseLogs", reflect.TypeOf((*MockServerManagerClient)(nil).DatabaseLogs), ctx, dbID, opts)
}

// DatabaseStatus mocks base method.
func (m *MockServerManagerClient) DatabaseStatus(ctx context.Context, dbID string) (*ports.DBStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseStatus", ctx, dbID)
	ret0, _ := ret[0].(*ports.DBStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DatabaseStatus indicates an expected call of DatabaseStatus.
func (mr *MockServerManagerClientMockRecorder) DatabaseStatus(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseStatus", reflect.TypeOf((*MockServerManagerClient)(nil).DatabaseStatus), ctx, dbID)
}

// Deploy mocks base method.
func (m *MockServerManagerClient) Deploy(ctx context.Context, appID string, spec ports.DeploySpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, appID, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deploy indicates an expected call of Deploy.
func (mr *MockServerManagerClientMockRecorder) Deploy(ctx, appID, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockServerManagerClient)(nil).Deploy), ctx, appID, spec)
}

// DeploymentStatus mocks base method.
func (m *MockServerManagerClient) DeploymentStatus(ctx context.Context, deploymentID string) (*ports.DeploymentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeploymentStatus", ctx, deploymentID)
	ret0, _ := ret[0].(*ports.DeploymentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeploymentStatus indicates an expected call of DeploymentStatus.
func (mr *MockServerManagerClientMockRecorder) DeploymentStatus(ctx, deploymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeploymentStatus", reflect.TypeOf((*MockServerManagerClient)(nil).DeploymentStatus), ctx, deploymentID)
}

// Logs mocks base method.
func (m *MockServerManagerClient) Logs(ctx context.Context, appID string, opts ports.LogOptions) ([]ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, appID, opts)
	ret0, _ := ret[0].([]ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockServerManagerClientMockRecorder) Logs(ctx, appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockServerManagerClient)(nil).Logs), ctx, appID, opts)
}

// ProvisionDatabase mocks base method.
func (m *MockServerManagerClient) ProvisionDatabase(ctx context.Context, dbID string, spec ports.DBProvisionSpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionDatabase", ctx, dbID, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionDatabase indicates an expected call of ProvisionDatabase.
func (mr *MockServerManagerClientMockRecorder) ProvisionDatabase(ctx, dbID, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionDatabase", reflect.TypeOf((*MockServerManagerClient)(nil).ProvisionDatabase), ctx, dbID, spec)
}

// Remove mocks base method.
func (m *MockServerManagerClient) Remove(ctx context.Context, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockServerManagerClientMockRecorder) Remove(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockServerManagerClient)(nil).Remove), ctx, appID)
}

// RemoveDatabase mocks base method.
func (m *MockServerManagerClient) RemoveDatabase(ctx context.Context, dbID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDatabase", ctx, dbID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDatabase indicates an expected call of RemoveDatabase.
func (mr *MockServerManagerClientMockRecorder) RemoveDatabase(ctx, dbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDatabase", reflect.TypeOf((*MockServerManagerClient)(nil).RemoveDatabase), ctx, dbID)
}

// Start mocks base method.
func (m *MockServerManagerClient) Start(ctx context.Context, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerManagerClientMockRecorder) Start(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServerManagerClient)(nil).Start), ctx, appID)
}

// Stop mocks base method.
func (m *MockServerManagerClient) Stop(ctx context.Context, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockServerManagerClientMockRecorder) Stop(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockServerManagerClient)(nil).Stop), ctx, appID)
}

// StreamDatabaseLogs mocks base method.
func (m *MockServerManagerClient) StreamDatabaseLogs(ctx context.Context, dbID string, opts ports.LogOptions) (<-chan ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamDatabaseLogs", ctx, dbID, opts)
	ret0, _ := ret[0].(<-chan ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamDatabaseLogs indicates an expected call of StreamDatabaseLogs.
func (mr *MockServerManagerClientMockRecorder) StreamDatabaseLogs(ctx, dbID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamDatabaseLogs", reflect.TypeOf((*MockServerManagerClient)(nil).StreamDatabaseLogs), ctx, dbID, opts)
}

// StreamLogs mocks base method.
func (m *MockServerManagerClient) StreamLogs(ctx context.Context, appID string, opts ports.LogOptions) (<-chan ports.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamLogs", ctx, appID, opts)
	ret0, _ := ret[0].(<-chan ports.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamLogs indicates an expected call of StreamLogs.
func (mr *MockServerManagerClientMockRecorder) StreamLogs(ctx, appID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamLogs", reflect.TypeOf((*MockServerManagerClient)(nil).StreamLogs), ctx, appID, opts)
}
