// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ports/deployment_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ports/deployment_repo.go -destination=internal/mocks/mock_deployment_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeploymentRepo is a mock of DeploymentRepo interface.
type MockDeploymentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentRepoMockRecorder
	isgomock struct{}
}

// MockDeploymentRepoMockRecorder is the mock recorder for MockDeploymentRepo.
type MockDeploymentRepoMockRecorder struct {
	mock *MockDeploymentRepo
}

// NewMockDeploymentRepo creates a new mock instance.
func NewMockDeploymentRepo(ctrl *gomock.Controller) *MockDeploymentRepo {
	mock := &MockDeploymentRepo{ctrl: ctrl}
	mock.recorder = &MockDeploymentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentRepo) EXPECT() *MockDeploymentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeploymentRepo) Create(deployment *domain.Deployment, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", deployment, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeploymentRepoMockRecorder) Create(deployment, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeploymentRepo)(nil).Create), deployment, arg1)
}

// FailInFlight mocks base method.
func (m *MockDeploymentRepo) FailInFlight(reason string, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailInFlight", reason, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailInFlight indicates an expected call of FailInFlight.
func (mr *MockDeploymentRepoMockRecorder) FailInFlight(reason, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailInFlight", reflect.TypeOf((*MockDeploymentRepo)(nil).FailInFlight), reason, arg1)
}

// ListByApplication mocks base method.
func (m *MockDeploymentRepo) ListByApplication(appID string, limit int, arg2 context.Context) ([]domain.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByApplication", appID, limit, arg2)
	ret0, _ := ret[0].([]domain.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByApplication indicates an expected call of ListByApplication.
func (mr *MockDeploymentRepoMockRecorder) ListByApplication(appID, limit, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByApplication", reflect.TypeOf((*MockDeploymentRepo)(nil).ListByApplication), appID, limit, arg2)
}

// UpdateByManagerID mocks base method.
func (m *MockDeploymentRepo) UpdateByManagerID(managerID string, updates map[string]any, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByManagerID", managerID, updates, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByManagerID indicates an expected call of UpdateByManagerID.
func (mr *MockDeploymentRepoMockRecorder) UpdateByManagerID(managerID, updates, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByManagerID", reflect.TypeOf((*MockDeploymentRepo)(nil).UpdateByManagerID), managerID, updates, arg2)
}
