// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/image_builder.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/image_builder.go -destination=internal/mocks/mock_image_builder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	domain "servermanager/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockImageBuilder is a mock of ImageBuilder interface.
type MockImageBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockImageBuilderMockRecorder
	isgomock struct{}
}

// MockImageBuilderMockRecorder is the mock recorder for MockImageBuilder.
type MockImageBuilderMockRecorder struct {
	mock *MockImageBuilder
}

// NewMockImageBuilder creates a new mock instance.
func NewMockImageBuilder(ctrl *gomock.Controller) *MockImageBuilder {
	mock := &MockImageBuilder{ctrl: ctrl}
	mock.recorder = &MockImageBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageBuilder) EXPECT() *MockImageBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockImageBuilder) Build(ctx context.Context, in domain.BuildInput, logSink io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, in, logSink)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockImageBuilderMockRecorder) Build(ctx, in, logSink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockImageBuilder)(nil).Build), ctx, in, logSink)
}
