// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/metrics_source.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/metrics_source.go -destination=internal/mocks/mock_metrics_source.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "servermanager/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsSource is a mock of MetricsSource interface.
type MockMetricsSource struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsSourceMockRecorder
	isgomock struct{}
}

// MockMetricsSourceMockRecorder is the mock recorder for MockMetricsSource.
type MockMetricsSourceMockRecorder struct {
	mock *MockMetricsSource
}

// NewMockMetricsSource creates a new mock instance.
func NewMockMetricsSource(ctrl *gomock.Controller) *MockMetricsSource {
	mock := &MockMetricsSource{ctrl: ctrl}
	mock.recorder = &MockMetricsSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsSource) EXPECT() *MockMetricsSourceMockRecorder {
	return m.recorder
}

// Sample mocks base method.
func (m *MockMetricsSource) Sample(ctx context.Context, containerID string) (domain.StatsSample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sample", ctx, containerID)
	ret0, _ := ret[0].(domain.StatsSample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sample indicates an expected call of Sample.
func (mr *MockMetricsSourceMockRecorder) Sample(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sample", reflect.TypeOf((*MockMetricsSource)(nil).Sample), ctx, containerID)
}
