// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/source_fetcher.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/source_fetcher.go -destination=internal/mocks/mock_source_fetcher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "servermanager/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockSourceFetcher is a mock of SourceFetcher interface.
type MockSourceFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockSourceFetcherMockRecorder
	isgomock struct{}
}

// MockSourceFetcherMockRecorder is the mock recorder for MockSourceFetcher.
type MockSourceFetcherMockRecorder struct {
	mock *MockSourceFetcher
}

// NewMockSourceFetcher creates a new mock instance.
func NewMockSourceFetcher(ctrl *gomock.Controller) *MockSourceFetcher {
	mock := &MockSourceFetcher{ctrl: ctrl}
	mock.recorder = &MockSourceFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceFetcher) EXPECT() *MockSourceFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockSourceFetcher) Fetch(ctx context.Context, repoURL, branch string) (*domain.SourceCheckout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, repoURL, branch)
	ret0, _ := ret[0].(*domain.SourceCheckout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockSourceFetcherMockRecorder) Fetch(ctx, repoURL, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockSourceFetcher)(nil).Fetch), ctx, repoURL, branch)
}
