// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/container_runtime.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/container_runtime.go -destination=internal/mocks/mock_container_runtime.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "servermanager/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerRuntime is a mock of ContainerRuntime interface.
type MockContainerRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockContainerRuntimeMockRecorder
	isgomock struct{}
}

// MockContainerRuntimeMockRecorder is the mock recorder for MockContainerRuntime.
type MockContainerRuntimeMockRecorder struct {
	mock *MockContainerRuntime
}

// NewMockContainerRuntime creates a new mock instance.
func NewMockContainerRuntime(ctrl *gomock.Controller) *MockContainerRuntime {
	mock := &MockContainerRuntime{ctrl: ctrl}
	mock.recorder = &MockContainerRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerRuntime) EXPECT() *MockContainerRuntimeMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContainerRuntime) Create(ctx context.Context, spec domain.ContainerSpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContainerRuntimeMockRecorder) Create(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContainerRuntime)(nil).Create), ctx, spec)
}

// FollowLogs mocks base method.
func (m *MockContainerRuntime) FollowLogs(ctx context.Context, nameOrID string, opts domain.LogOptions) (<-chan domain.LogLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowLogs", ctx, nameOrID, opts)
	ret0, _ := ret[0].(<-chan domain.LogLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowLogs indicates an expected call of FollowLogs.
func (mr *MockContainerRuntimeMockRecorder) FollowLogs(ctx, nameOrID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowLogs", reflect.TypeOf((*MockContainerRuntime)(nil).FollowLogs), ctx, nameOrID, opts)
}

// Inspect mocks base method.
func (m *MockContainerRuntime) Inspect(ctx context.Context, nameOrID string) (*domain.ContainerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, nameOrID)
	ret0, _ := ret[0].(*domain.ContainerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockContainerRuntimeMockRecorder) Inspect(ctx, nameOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockContainerRuntime)(nil).Inspect), ctx, nameOrID)
}

// Logs mocks base method.
func (m *MockContainerRuntime) Logs(ctx context.Context, nameOrID string, opts domain.LogOptions) ([]domain.LogLine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, nameOrID, opts)
	ret0, _ := ret[0].([]domain.LogLine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockContainerRuntimeMockRecorder) Logs(ctx, nameOrID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockContainerRuntime)(nil).Logs), ctx, nameOrID, opts)
}

// Remove mocks base method.
func (m *MockContainerRuntime) Remove(ctx context.Context, nameOrID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, nameOrID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockContainerRuntimeMockRecorder) Remove(ctx, nameOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockContainerRuntime)(nil).Remove), ctx, nameOrID)
}

// Start mocks base method.
func (m *MockContainerRuntime) Start(ctx context.Context, nameOrID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, nameOrID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockContainerRuntimeMockRecorder) Start(ctx, nameOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockContainerRuntime)(nil).Start), ctx, nameOrID)
}

// Stop mocks base method.
func (m *MockContainerRuntime) Stop(ctx context.Context, nameOrID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, nameOrID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockContainerRuntimeMockRecorder) Stop(ctx, nameOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockContainerRuntime)(nil).Stop), ctx, nameOrID)
}
