// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/container_exec.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/container_exec.go -destination=internal/mocks/mock_container_exec.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerExec is a mock of ContainerExec interface.
type MockContainerExec struct {
	ctrl     *gomock.Controller
	recorder *MockContainerExecMockRecorder
	isgomock struct{}
}

// MockContainerExecMockRecorder is the mock recorder for MockContainerExec.
type MockContainerExecMockRecorder struct {
	mock *MockContainerExec
}

// NewMockContainerExec creates a new mock instance.
func NewMockContainerExec(ctrl *gomock.Controller) *MockContainerExec {
	mock := &MockContainerExec{ctrl: ctrl}
	mock.recorder = &MockContainerExecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerExec) EXPECT() *MockContainerExecMockRecorder {
	return m.recorder
}

// ContainerEnv mocks base method.
func (m *MockContainerExec) ContainerEnv(ctx context.Context, nameOrID string, keys ...string) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, nameOrID}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ContainerEnv", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerEnv indicates an expected call of ContainerEnv.
func (mr *MockContainerExecMockRecorder) ContainerEnv(ctx, nameOrID any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, nameOrID}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerEnv", reflect.TypeOf((*MockContainerExec)(nil).ContainerEnv), varargs...)
}

// ExecCapture mocks base method.
func (m *MockContainerExec) ExecCapture(ctx context.Context, nameOrID string, argv []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCapture", ctx, nameOrID, argv)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecCapture indicates an expected call of ExecCapture.
func (mr *MockContainerExecMockRecorder) ExecCapture(ctx, nameOrID, argv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCapture", reflect.TypeOf((*MockContainerExec)(nil).ExecCapture), ctx, nameOrID, argv)
}
